In [1]:
import pandas as pd

In [2]:
county_race = pd.read_csv("county_racial.csv")
county_race.head()

,GEO_ID,NAME,B02001_001E,B02001_001M,B02001_002E,B02001_002M,B02001_003E,B02001_003M,B02001_004E,B02001_004M,...,B02001_006E,B02001_006M,B02001_007E,B02001_007M,B02001_008E,B02001_008M,B02001_009E,B02001_009M,B02001_010E,B02001_010M
0,id,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,Estimate!!Total:!!White alone,Margin of Error!!Total:!!White alone,Estimate!!Total:!!Black or African American alone,Margin of Error!!Total:!!Black or African Amer...,Estimate!!Total:!!American Indian and Alaska N...,Margin of Error!!Total:!!American Indian and A...,...,Estimate!!Total:!!Native Hawaiian and Other Pa...,Margin of Error!!Total:!!Native Hawaiian and O...,Estimate!!Total:!!Some other race alone,Margin of Error!!Total:!!Some other race alone,Estimate!!Total:!!Two or more races:,Margin of Error!!Total:!!Two or more races:,Estimate!!Total:!!Two or more races:!!Two race...,Margin of Error!!Total:!!Two or more races:!!T...,Estimate!!Total:!!Two or more races:!!Two race...,Margin of Error!!Total:!!Two or more races:!!T...
1,0500000US01003,"Baldwin County, Alabama",223234,*****,190912,2259,18338,1834,2428,1195,...,0,206,4685,2280,4711,2205,0,206,4711,2205
2,0500000US01015,"Calhoun County, Alabama",113605,*****,82323,1330,25226,1306,201,243,...,85,130,3186,1802,2359,1184,0,206,2359,1184
3,0500000US01043,"Cullman County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0500000US01049,"DeKalb County, Alabama",71513,*****,59305,1375,688,434,792,740,...,339,405,8327,1548,2045,913,8,18,2037,915

In [3]:
county_covid_deaths = pd.read_csv("Provisional_COVID-19_Death_Counts_by_County_and_Race.csv")
county_covid_deaths.head()

,Data as of,Start Date,End Date,State,County Name,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,...,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,Footnote
0,03/24/2021,01/01/2020,03/20/2021,AK,Anchorage Municipality,3,2,20,2020,Distribution of all-cause deaths (%),...,185,0.578,0.046,0.212,0.058,0.029,0.032,0.046,Medium metro,NaN
1,03/24/2021,01/01/2020,03/20/2021,AK,Anchorage Municipality,3,2,20,2020,Distribution of COVID-19 deaths (%),...,185,0.324,NaN,0.335,0.146,0.086,NaN,NaN,Medium metro,Data based on counts less than 10 suppressed
2,03/24/2021,01/01/2020,03/20/2021,AK,Anchorage Municipality,3,2,20,2020,Distribution of population (%),...,185,0.556,0.052,0.081,0.095,0.026,0.091,0.099,Medium metro,NaN
3,03/24/2021,01/01/2020,03/20/2021,AL,Baldwin County,4,1,3,1003,Distribution of all-cause deaths (%),...,243,0.902,0.078,NaN,NaN,NaN,0.013,NaN,Small metro,Data based on counts less than 10 suppressed
4,03/24/2021,01/01/2020,03/20/2021,AL,Baldwin County,4,1,3,1003,Distribution of COVID-19 deaths (%),...,243,0.860,0.115,NaN,NaN,NaN,NaN,NaN,Small metro,Data based on counts less than 10 suppressed